Repository umc-artistack/artistack-server, pull requests merged in 2022-08, with the labels that each got.

#45 12 회원 관련 API - 애플로그인
  build.gradle
  src/main/java/com/artistack/oauth/controller/OAuthController.java
  src/main/java/com/artistack/oauth/domain/AppleAccount.java
  src/main/java/com/artistack/oauth/dto/AppleAccountDto.java
  src/main/java/com/artistack/oauth/dto/ApplePublicKeyDto.java
  src/main/java/com/artistack/oauth/dto/AppleTokenDto.java
  src/main/java/com/artistack/oauth/repository/AppleAccountRepository.java
  src/main/java/com/artistack/oauth/service/OAuthService.java
  src/main/java/com/artistack/user/service/UserService.java
  src/main/resources/application.properties
  src/test/java/com/artistack/controller/OAuthControllerTest.java
  src/test/java/com/artistack/controller/ProjectControllerTest.java
Labels: fix, feat, 메이슨

#47 Feature/#40 - 좋아요 누른 사람 조회 API, 좋아요 여부 확인 코드 추가
  src/main/java/com/artistack/base/constant/Code.java
  src/main/java/com/artistack/project/controller/ProjectController.java
  src/main/java/com/artistack/project/domain/Project.java
  src/main/java/com/artistack/project/dto/ProjectDto.java
  src/main/java/com/artistack/project/repository/ProjectLikeRepository.java
  src/main/java/com/artistack/project/repository/ProjectRepository.java
  src/main/java/com/artistack/project/service/ProjectService.java
  src/main/java/com/artistack/user/dto/UserDto.java
Labels: feat, 셀리나

#49 project list 응답 형식, header 범위
  src/main/java/com/artistack/config/SecurityConfig.java
  src/main/java/com/artistack/project/dto/ProjectDto.java
  src/main/java/com/artistack/project/service/ProjectService.java
  src/test/java/com/artistack/controller/ProjectControllerTest.java
Labels: fix, 메이슨

#50 Feature/#13 스택 조회 API 페이징, 본인 포함 옵션 추가, 모든 프로젝트 조회 API 스택커 resposne 수정
  src/main/java/com/artistack/project/controller/ProjectController.java
  src/main/java/com/artistack/project/dto/ProjectDto.java
  src/main/java/com/artistack/project/service/ProjectService.java
  src/main/java/com/artistack/user/dto/UserDto.java
Labels: fix, feat, refactor, 제이

#51 Hotfix/#8 - 프로젝트 정보 조회 API 예외 처리
  src/main/java/com/artistack/base/constant/Code.java
  src/main/java/com/artistack/project/service/ProjectService.java
  src/main/java/com/artistack/user/dto/UserDto.java
Labels: fix, 셀리나
